is3d: true
checkpoints:
  continue_training: false
  test_mode: false
  ckpt_path: '/cabinet/yousef/brats2018/tb_logs/UNETR3D_AdamW/version_0/UNETR3D_AdamW-epoch=983-val_loss=0.1389.ckpt'
  log_pictures: false
dataset:
  name: "brats2021_loader"
  input_size: [128,128,128]
  train:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2021/data"
      normalization: true
      augmentation: true  
      p: 0.5
      
  validation:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2021/data"
      normalization: true
      augmentation: false
        
  test:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2021/data"
      normalization: true
      augmentation: false  
      
  test_split: 0.15
  validation_split: 0.05
data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  validation: 
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  test:
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: false
    persistent_workers: true
    
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.05
  criterion:     
    params: 
      dice_weight: 0.5
      bce_weight: 0.5
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 9
        mode: 'min'
  epochs: 300

model: 
  name: 'VNet_SGD_128'
  params:
    n_channels: 4
    n_classes: 4

use_sliding_window: true
sliding_window_params:
  overlap: 0.75
  mode: 'gaussian'