is3d: true
checkpoints:
  continue_training: true
  test_mode: false
  ckpt_path: '/cabinet/yousef/brats2018/tb_logs/UNETR3D_AdamW/version_0/UNETR3D_AdamW-epoch=983-val_loss=0.1389.ckpt'
  log_pictures: false
dataset:
  name: "brats_2018_loader"
  input_size: [96,96,96]
  train:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: true  
      p: 0.5
      
  validation:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: false
        
  test:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: false  
      
  test_split: 0.2
  validation_split: 0.1
data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  validation: 
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  test:
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: false
    persistent_workers: true
training:
  optimizer:
    name: 'AdamW'
    params:
      lr: 0.0001
  criterion:    
    params: 
      dice_weight: 0.5
      bce_weight: 0.5
      global_weight: 1
      blob_weight: 0.0
      blob_params:
        hd_loss: false
        dice_loss: true
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 7
        mode: 'min'
  epochs: 1000
model: 
  name: 'UNETR3D_AdamW'
  params:
    img_size: [96,96,96]
    spatial_dims: 3
    in_channels: 4
    out_channels: 4
use_sliding_window: true
sliding_window_params:
  overlap: 0.75
  mode: 'gaussian'

