is3d: true
checkpoints:
  continue_training: false
  test_mode: false
  ckpt_path: 'E:/brats2018/tb_logs/UNet3D_SGD/version_7/UNet3D_SGD-epoch=00-val_loss=0.2970.ckpt'
  log_pictures: false

dataset:
  name: "brats_2018_loader"
  input_size: [96,96,96]
  train:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      p: 0.5
  validation:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
  test:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
  test_split: 0.2
  validation_split: 0.1

data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  validation: 
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  test:
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: false
    persistent_workers: true

training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.05
  criterion:     
    params: 
      dice_weight: 0.5
      bce_weight: 0.5
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 7
        mode: 'min'
  epochs: 300

model: 
  name: 'UNet3D_SGD'
  params:
    in_channels: 4
    out_channels: 4
    f_maps: 32

use_sliding_window: true
sliding_window_params:
  overlap: 0.75
  mode: 'gaussian'