is3d: true
checkpoints:
  continue_training: false
  test_mode: false
  ckpt_path: 'saved_models/met_unet/TranscUnet_Adam_2021-10-20_16-00-00/checkpoints/epoch=299.ckpt'
  log_pictures: false
dataset:
  name: "brats_2018_loader"
  input_size: [96,96,96]
  train:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: true  
      p: 0.5

  validation:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: false  

  test:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: false  

  test_split: 0.2
  validation_split: 0.1

data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  validation: 
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  test:
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: false
    persistent_workers: true
    
training:
  optimizer:
    name: 'AdamW'
    params:
      lr: 0.0002
  criterion:
    params: 
      dice_weight: 0.5
      bce_weight: 0.5
  scheduler:
    name: 'LinearWarmupCosineAnnealingLR'
    params:
        warmup_epochs: 20
        max_epochs: 1000
        warmup_start_lr: 0.000001
  epochs: 1000
  
model: 
  name: 'MainModel_AdamW_afshin_dnnn_CosineAnnealingLR'
  params:
    spatial_shapes: [96, 96, 96]
    in_channels: 4
    out_channels: 4
                 
    # encoder params
    cnn_kernel_sizes: [5,3]
    cnn_features: [16,16]
    cnn_strides: [2,2]
    cnn_maxpools: [false, true]
    cnn_dropouts: 0.0
    hyb_kernel_sizes: [3,3,3]
    hyb_features: [32,64,128]
    hyb_strides: [2,2,2]
    hyb_maxpools: [true, true, true]
    hyb_cnn_dropouts: 0.0
    hyb_tf_proj_sizes: [32,64,64]
    hyb_tf_repeats: [1,1,1]
    hyb_tf_num_heads: [2,4,8]
    hyb_tf_dropouts: 0.15
    cnn_deforms: [true, true]
    hyb_use_cnn: [true,true,true]
    hyb_deforms: [false,false,false]

    # decoder params
    dec_hyb_tcv_kernel_sizes: [5,5,5]
    dec_cnn_tcv_kernel_sizes: [5,7]
    
    dec_hyb_kernel_sizes: null
    dec_hyb_features: null
    dec_hyb_cnn_dropouts: null
    dec_hyb_tf_proj_sizes: null
    dec_hyb_tf_repeats: null
    dec_hyb_tf_num_heads: null
    dec_hyb_tf_dropouts: null
    dec_cnn_kernel_sizes: null
    dec_cnn_features: null
    dec_cnn_dropouts: null

    dec_cnn_deforms: [false, false]
    dec_hyb_deforms: null

use_sliding_window: true
sliding_window_params:
  overlap: 0.75
  mode: 'gaussian'