is3d: true
checkpoints:
  continue_training: false
  test_mode: false
  ckpt_path: 'saved_models/met_unet/TranscUnet_Adam_2021-10-20_16-00-00/checkpoints/epoch=299.ckpt'
  log_pictures: false
dataset:
  name: "brats_2018_loader"
  input_size: [96,96,96]
  train:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: true  
      p: 0.5
      
  validation:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: false  
      
  test:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: false  
      
  test_split: 0.2
  validation_split: 0.1
data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  validation: 
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  test:
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: false
    persistent_workers: true
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      momentum: 0.99
      weight_decay : 0.00003
      nesterov: true
  criterion:     
    params: 
      dice_weight: 0.5
      bce_weight: 0.5
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 7
        mode: 'min'
  epochs: 500
model: 
  name: 'DLK-Former_SGD_without_deep'
  params:
    in_channels: 4
    out_channels: 4
    img_size: [96, 96, 96]
    patch_size: [2,2,2]
    input_size: [110592, 13824,1728,216]
    do_ds: False

use_sliding_window: true
sliding_window_params:
  overlap: 0.5
  mode: 'gaussian'