is3d: true
checkpoints:
  continue_training: false
  test_mode: false
  ckpt_path: 'saved_models/met_unet/TranscUnet_Adam_2021-10-20_16-00-00/checkpoints/epoch=299.ckpt'
  log_pictures: false
dataset:
  name: "acdc_v2_loader"
  input_size: [160,160,14]
  train:
    params:
      # data_root: "D:\\DATASETS\\ACDC\\ACDC\\database\\training"
      data_root: "/cabinet/dataset/ACDC/ACDC/database/3Ddata"
      normalization: true
      augmentation: true  
      p: 0.5
      
  validation:
    params:
      # data_root: "D:\\DATASETS\\ACDC\\ACDC\\database\\training"
      data_root: "/cabinet/dataset/ACDC/ACDC/database/3Ddata"
      normalization: true
      augmentation: false  
      
  test:
    params:
      # data_root: "D:\\DATASETS\\ACDC\\ACDC\\database\\training"
      data_root: "/cabinet/dataset/ACDC/ACDC/database/3Ddata"
      normalization: true
      augmentation: false  
      
  test_split: 0.2
  validation_split: 0.1
data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  validation: 
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  test:
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: false
    persistent_workers: true
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      momentum: 0.99
      weight_decay : 0.00003
      nesterov: true
  criterion:     
    params: 
      dice_weight: 0.5
      bce_weight: 0.5
  scheduler:
    name: 'CustomDecayLR'
    params:
      max_epochs: 1000
  epochs: 1000
model: 
  name: 'nnFormer3d_SGD_without_deep_V2'
  params:
    crop_size: [14,160,160]
    input_channels: 1
    num_classes: 4
    deep_supervision: false
    patch_size: [1,4,4]
    window_size: [[3,5,5],[3,5,5],[7,10,10],[3,5,5]]
    num_heads: [3, 6, 12, 24]
    embedding_dim: 96
    down_stride: [[1,4,4],[1,8,8],[2,16,16],[4,32,32]] 
use_sliding_window: true
sliding_window_params:
  overlap: 0.75
  mode: 'gaussian'