is3d: true
checkpoints:
  continue_training: false
  test_mode: false
  ckpt_path: 'saved_models/met_unet/TranscUnet_Adam_2021-10-20_16-00-00/checkpoints/epoch=299.ckpt'
  log_pictures: false
dataset:
  name: "brats_2018_loader"
  input_size: [96,96,96]
  train:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: true  
      p: 0.5
      
  validation:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: false  
      
  test:
    params:
      # data_root: "E:/Brats 2018 data"
      data_root: "/cabinet/dataset/brats/Brats 2018"
      normalization: true
      augmentation: false  
      
  test_split: 0.2
  validation_split: 0.1
data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  validation: 
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: true
    persistent_workers: true
  test:
    batch_size: 1
    shuffle: false
    num_workers: 14
    pin_memory: false
    persistent_workers: true
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      momentum: 0.99
      weight_decay : 0.00003
      nesterov: true
  criterion:     
    params: 
      dice_weight: 0.5
      bce_weight: 0.5
  scheduler:
    name: 'CustomDecayLR'
    params:
      max_epochs: 1000
  epochs: 1000
model: 
  name: 'nnFormer3d_SGD_without_deep'
  params:
    crop_size: [96,96,96]
    input_channels: 4
    num_classes: 4
    deep_supervision: false
    patch_size: [4,4,4]
    window_size: [4,4,8,4]
    num_heads: [3, 6, 12, 24]
    embedding_dim: 96
use_sliding_window: true
sliding_window_params:
  overlap: 0.75
  mode: 'gaussian'